#!/bin/bash --login
current=${PWD}
git_root=$(git rev-parse --show-toplevel)
cd $git_root
if [[ "$(which virtualenv)" == "" ]]; then
    echo "INSTALLING TOOLS: "
    sudo apt-get update
    sudo apt-get install software-properties-common python-dev python-pip -y
    sudo pip install virtualenv
fi
if [[ ! -d ${git_root}/env ]]; then
    /usr/local/bin/virtualenv ${git_root}/env
fi
source ${git_root}/env/bin/activate
cd $current
