#!/bin/bash --login
CCORD_DIR=$(dirname $(readlink -f "$0"))
export PATH=${PATH}:${CCORD_DIR}

case ${1} in
    graph)
        shift
        python concord_cli/print_graph "$@"
        ;;
    deploy)
        shift
        python -m concord_cli/deploy "$@"
        ;;
    kill)
        shift
        python -m concord_cli/kill_task "$@"
        ;;
    scale)
        shift
        python -m concord_cli/scale "$@"
        ;;
    trace)
        shift
        python -m concord_cli/tracer "$@"
        ;;
    *)
        echo "Usage: "
        echo "concord [program] [flags] "
        echo "concord (graph|kill|deploy|scale|trace) -h"
        ;;
esac
