#!/bin/bash --login


case ${1} in
    config)
        shift
        python2.7 -m concord_cli/config "$@"
        ;;
    graph)
        shift
        python2.7 -m concord_cli/print_graph "$@"
        ;;
    deploy)
        shift
        python2.7 -m concord_cli/deploy "$@"
        ;;
    kill)
        shift
        python2.7 -m concord_cli/kill_task "$@"
        ;;
    *)
        echo "Usage: "
        echo "concord [program] [flags] "
        echo "concord (config|graph|kill|deploy) -h"
        ;;
esac
